[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"
  source = "https://github.com/jessevdk/go-flags.git"

[[constraint]]
  name = "github.com/mcuadros/go-defaults"
  revision = "e1c978be3307be96ef03a0bd25d719ab50d277e4"
  source = "https://github.com/mcuadros/go-defaults.git"

[[constraint]]
  name = "github.com/src-d/envconfig"
  revision = "34ca5bb0e3815d60fe5008b1dd188beb83e2e7df"
  source = "https://github.com/src-d/envconfig.git"

[[constraint]]
  name = "gopkg.in/check.v1"
  branch = "v1"
  source = "https://github.com/go-check/check.git"

[[constraint]]
  name = "gopkg.in/inconshreveable/log15.v2"
  version = "2.13.0"
  source = "https://github.com/inconshreveable/log15.git"

[[constraint]]
  name = "gopkg.in/jarcoal/httpmock.v1"
  branch = "v1"
  source = "https://github.com/jarcoal/httpmock.git"

[[constraint]]
  name = "gopkg.in/src-d/go-kallax.v1"
  branch = "master"
  source = "https://github.com/src-d/go-kallax.git"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"
  source = "https://github.com/satori/go.uuid.git"
