apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rovers
spec:
  template:
    metadata:
      labels:
        app: rovers
    spec:
      containers:
      - name: rovers
        image: quay.io/srcd/rovers:v2.6.0
        args:
        - "rovers"
        - "repos"
        env:
        - name: CONFIG_DBUSER
          value: testing
        - name: CONFIG_DBPASS
          value: testing
        - name: CONFIG_DBHOST
          value: postgres
        - name: CONFIG_DBNAME
          value: testing
        - name: CONFIG_BROKER_URL
          value: amqp://guest:guest@rabbitmq:5672/
        - name: CONFIG_GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: rovers-secrets
              key: github
        - name: CONFIG_BING_KEY
          valueFrom:
            secretKeyRef:
              name: rovers-secrets
              key: bing
      imagePullSecrets:
      - name: quay
